# Should Admins Be Alerted When Someone Is Warned? (true/false)
Alert Admins: True
# Customisable Messages
Warning Message: You have been warned please follow the /rules
Warning For: You have been warned for
# Warnings Before Event
Kick After: 3
Ban After: 5
# Messages For Events
Kick Message: Please read the /rules!
Ban Message: You have been banned for having too many warnings!
# Should Remaining Warnings Be Displayed?
Show Remaining: True
Auto Update: True
# Player Information
# Should players be informed that this server is protected by Kustom Warn
Alert Players: True
