name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
database: true
version: ${project.version}
author: ${project.author}
description: ${project.description}
commands:
    kwarn:
        usage: /<command> [player] (reason)
        description: Used to warn the player, reason is optional
        permission: kustomwarn.warn
        default: op
    klist:
        usage: /<command> [player]
        description: List your warnings
        permission: kustomwarn.listself
        default: op
    kwarns:
        usage: /<command>
        description: List another players warnings
        permission: kustomwarn.list
        default: true
    kdelete:
        usage: /<command> [player] [warning-number]
        description: Delete a players warning(s)
        permission: kustomwarn.delete
        default: op
    kreload:
        usage: /<command>
        description: Reloads the plugin configuration file (config.yml)
        permission: kustomwarn.reload
        default: op
    kreset:
        usage: /<command> [player]
        description: Allows you to reset a players warnings to zero
        permission: kustomwarn.reset
        default: op